export const initialData = {
    mapTitle: "MyHomelab",
    nodes: [
        {
            id: "router-1",
            type: "router",
            x: 400,
            y: 50,
            data: {
                name: "Main Router",
                subtitle: "",
                ip: "192.168.1.1",
                outPorts: 4,
                specs: [],
                components: [],
            },
        },
        {
            id: "switch-1",
            type: "switch",
            x: 400,
            y: 250,
            data: {
                name: "Core Switch",
                subtitle: "",
                ip: "192.168.1.10",
                outPorts: 8,
                specs: [],
                components: [],
            },
        },
        {
            id: "server-1",
            type: "server",
            x: 100,
            y: 400,
            data: {
                name: "Proxmox-NAS",
                subtitle: "Lenovo M920q",
                ip: "192.168.1.180",
                specs: ["6 Cores", "16GB RAM", "256GB Disk"],
                outPorts: 1,
                components: [
                    { id: "comp-1", type: "hba", name: "HBA to disks" },
                    { id: "comp-2", type: "disk", name: '2.5" Disk 1' },
                    { id: "comp-3", type: "disk", name: '2.5" Disk 2' },
                    { id: "comp-4", type: "disk", name: '2.5" Disk 3' },
                    { id: "comp-5", type: "disk", name: '2.5" Disk 4' },
                ],
                subItems: [
                    {
                        id: "sub-1",
                        name: "Immich",
                        ip: "192.168.1.3",
                        type: "container",
                    },
                    {
                        id: "sub-2",
                        name: "Jellyfin",
                        ip: "192.168.1.4",
                        type: "container",
                    },
                    {
                        id: "sub-3",
                        name: "Nextcloud",
                        ip: "192.168.1.5",
                        type: "container",
                    },
                ],
            },
        },
        {
            id: "server-2",
            type: "server",
            x: 700,
            y: 400,
            data: {
                name: "Raspberry Pi 4",
                subtitle: "Raspberry Pi 4 (4GB BCM2711)",
                ip: "192.168.1.200",
                specs: ["4 Cores", "4GB RAM"],
                outPorts: 1,
                components: [],
                subItems: [
                    {
                        id: "sub-4",
                        name: "Uptime Kuma",
                        ip: "192.168.1.181",
                        type: "container",
                    },
                    {
                        id: "sub-5",
                        name: "Grafana",
                        ip: "192.168.1.182",
                        type: "container",
                    },
                    {
                        id: "sub-6",
                        name: "Pi-hole",
                        ip: "192.168.1.183",
                        type: "container",
                    },
                ],
            },
        },
    ],
    edges: [
        {
            id: "e1",
            sourceNode: "router-1",
            sourceType: "out",
            sourceIndex: 1,
            targetNode: "switch-1",
            targetType: "in",
            targetIndex: 0,
        },
        {
            id: "e2",
            sourceNode: "switch-1",
            sourceType: "out",
            sourceIndex: 1,
            targetNode: "server-1",
            targetType: "in",
            targetIndex: 0,
        },
        {
            id: "e3",
            sourceNode: "switch-1",
            sourceType: "out",
            sourceIndex: 6,
            targetNode: "server-2",
            targetType: "in",
            targetIndex: 0,
        },
    ],
};
